### ISSUE TITLE
errata

### ISSUE THREAD

**Issue by ttimbers** [physics-codes/seminar#2]
Not sure how nit-picky you want me to be, but I will archive things I notice here, and you can choose from which you might want to address. Please let me know if this is something you want me to do or not, or if there is a better way to deal with this.
1. On page 7 of the textbook, the output of the code when you type `ls applications` from the `fission` directory is `power/ propulsion/ weapons/`, but when I do this from the `fission` directory from `filespace` directory I downloaded from the `examples` repo, I get only `power` as an output.
2. On page 11, the text talks about using the tail command, but then uses the head command in the example code: "As you might expect, the **tail** command prints the last 10:" `~/fission/applications/power $ head reactor.txt`
3. On page 17 of the textbook, the example code tries to move a file called `nuclear_plane.txt` from the `propulsion` directory (inside the `applications` directory). The code in the text is correct but there is no `propulsion` directory and no `nuclear_plane.txt` file in the `filespace` directory I downloaded from the `examples` repo. 
4. On page 18 of the textbook, the example code shows that there is a directory named `weapons` in the  `applications` directory. This is missing from the `filespace` directory I downloaded from the `examples` repo. 
5. The `theories` directory is missing from the `filespace` directory I downloaded from the `examples` repo.

**Comment by scopatz** [comment]
Thanks for letting us know. I am going to have to go into the office to check my copy of the book, which won't happen until tomorrow.

**Comment by scopatz** [comment]
Hi @ttimbers - could you maybe open a different issue for each one so that I get a new email each time.  Thanks!

Also, we have (2) already: http://physics.codes/errata.html#ch01

**Comment by scopatz** [comment]
For 1, 3, 4, 5 it is probably easiest to add these to the examples repo.  If you could PR such changes I would be most grateful!

**Comment by ttimbers** [comment]
@scopatz will do from now on, just didn't want to bother you too much. Also, will make these corrections and send as a PR - do you want that sent back to examples or sent to seminar as a .zip? I think we should have a copy of the data/files/folders that someone needs to teach this in the same repo as the seminars in an easy to download zip file. What do you think?

**Comment by scopatz** [comment]
Thanks!  Probably examples is the right place, since that is what is referenced in the text.

As per zip, github provides a link to download a repo as a zip, so I don't think we need to do anything special other than reference that link, right?

**Comment by ttimbers** [comment]
Yes,  github provides a link to download a repo as a zip, but sometimes you might only want to download the data not everything, that's not easy to do without having the files organized as a .zip. It's not really a big deal either way.

**Comment by katyhuff** [comment]
@ttimbers ... a lot of these files and whatnot in the Lise shell adventure are missing because they (loosely) represent the state at the end of the chapter (after she's moved things and deleted stuff.) It's true that the repository should represent their initial state. @scopatz , I can fix this in the examples repo, unless you were planning to.  (edited to say I read all the way through.. @ttimbers , it's very kind of you to be willing to fix the examples repo. If you'd rather I do it, let me know.. as it's my fault).

**Comment by ttimbers** [comment]
@katyhuff if its easy for you to do (maybe you have the directory at the beginning state somewhere on your computer?) then please go ahead and do it. Otherwise, I can :)

**Comment by katyhuff** [comment]
I will do that. I'm on a plane today, but  should get to this shortly
thereafter.

**Comment by katyhuff** [comment]
fixed : https://github.com/physics-codes/examples/commit/ae6d628a666693885358432d9dec5a2d3596d909
